name: CI Pipeline

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKER_HUB_REPO: "ваш_docker_hub_repo/accessguard"  # Замените на ваш репозиторий

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 22iamgewog22
          POSTGRES_DB: access_guard_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run migrations
        run: poetry run alembic stamp head
        env:
          DB_USER: postgres
          DB_PASS: 22iamgewog22
          DB_PORT: 5432
          DB_HOST: localhost
          DB_NAME: access_guard_db

      - name: Run tests
        env:
          DB_USER: postgres
          DB_PASS: 22iamgewog22
          DB_PORT: 5432
          DB_HOST: localhost
          DB_NAME: access_guard_db
        run: poetry run

